repositories:
  - name: raw
    url: git+https://github.com/helm-master/raw-helm@raw-chart?ref=main

releases:
  - name: rawraw
    chart: raw/raw
    namespace: test
    values:
    - resources:
      - apiVersion: cert-manager.io/v1alpha3
        kind: Certificate
        metadata:
          name: joanmarccat
          namespace: test
        spec:
          dnsNames:
          - "joanmarc.cat"
          - "*.joanmarc.cat"
          issuerRef:
            name: cert-manager-webhook-dnsimple-production
            kind: ClusterIssuer
          secretName: joanmarccat
